### ISSUE TITLE
Swift Decode Geometry to get route array for polylines

### ISSUE THREAD

**Issue by ghost** [mappls-api/mapmyindia-maps-vectorSDK-iOS#1]
How to decode the "geometry": "osgmDutwuMjA~@vEfGx@X~RlXLnAhGbJfHjQzBxDb@jEpAj@nAFt@`A?fAQn@aDbBcAhBmChQ", 
by using swift or how to use  your Javascript code to draw the polyline in map sdk

**Comment by spacekingindia** [comment]
To decode geometry, use library "Polyline" to convert into array of coordinates or locations in swift. Below is link to document section of decoding and github page of "Polyline" library:
https://github.com/raphaelmor/Polyline#polyline-decoding

**Comment by ghost** [comment]
thanks for the link. let me try . currently am using _**let context = JSContext() context?.evaluateScript(jsSource)**_ to convert the decode string to coordinates.
