### ISSUE TITLE
Facing issue on Xcode 13.2.1 

### ISSUE THREAD

**Issue by ashwani280496** [mappls-api/mapmyindia-maps-vectorSDK-iOS#12]
it throws compiled time error 
import MapmyIndiaDirections //Module compiled with Swift 5.5 cannot be imported by the Swift 5.5.2 compiler

**Comment by sathishvudugundla** [comment]
I am also facing the same issue can any one please help

**Comment by sathishvudugundla** [comment]
> it throws compiled time error import MapmyIndiaDirections //Module compiled with Swift 5.5 cannot be imported by the Swift 5.5.2 compiler

Hello Ashwani, Did you find any solution ?

**Comment by spacekingindia** [comment]
> it throws compiled time error import MapmyIndiaDirections //Module compiled with Swift 5.5 cannot be imported by the Swift 5.5.2 compiler

For which framework you are facing the problem?

Just for information all 5.5.2 compatible framework are available, Please check which version is getting installed while installing through CocoaPods. [MapmyIndiaAPIKit](https://github.com/MapmyIndia/mapmyindia-maps-vectorSDK-iOS/blob/master/docs/v1.0.3/REST-API-Kit.md#Version-History), [MapmyIndiaDirections](https://github.com/MapmyIndia/mapmyindia-maps-vectorSDK-iOS/blob/master/docs/v1.0.3/MapmyIndiaDirections.md#MapmyIndiaDirections)
For more info to pull latest pod see [pod install vs. pod update](https://guides.cocoapods.org/using/pod-install-vs-update.html)

**Comment by mahendraTP** [comment]
any solution for this?

**Comment by mdakram** [comment]
@mahendraTP please check @spacekingindia comment.

**Comment by mahendraTP** [comment]
Target->Build setting->excluded architecture->Add 'any iOS simulator'- arm64
Do same for Pods also.
