### ISSUE TITLE
Code signing "Mapbox.framework" failed.

### ISSUE THREAD

**Issue by ghost** [mappls-api/mapmyindia-maps-vectorSDK-iOS#3]
Hi, when i try upload it to testfilght i am getting this error.

from IDEDistribution.standard..log

<IDEDistributionContext: 0x7fb77a1c3880; archive = '<IDEArchive: 0x7fb77a347200>', distributionMethod='(null)', team='(null)'>
</IDEDistributionContext: 0x7fb779f97400>

if i remove the framework files  from the Embedded binaries, I could able to upload perfectly. what could be the issue.

**Comment by ayushdayal007** [comment]
This is issue of simulator architecture existence in dynamic frameworks.
See [here](https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive).
Also this can be resolved by following step no 3 from section "Setup Your project".
