### ISSUE TITLE
When i integrated MapMyIndia then i got this error.  dyld: dyld cache load error: shared cache file open() failed dyld: Library not loaded: @rpath/MapmyIndiaAPIKit.framework/MapmyIndiaAPIKit

### ISSUE THREAD

**Issue by HimanshuGupta001** [mappls-api/mapmyindia-maps-vectorSDK-iOS#5]
dyld: dyld cache load error: shared cache file open() failed
dyld: Library not loaded: @rpath/MapmyIndiaAPIKit.framework/MapmyIndiaAPIKit

**Comment by ayushdayal007** [comment]
Kindly go to Troubleshooting section in [Wiki](https://github.com/MapmyIndia/mapmyindia-maps-vectorSDK-iOS-sample-withREST-beta/wiki) for this problem.
