### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compile

### ISSUE THREAD

**Issue by jaindiv26** [mappls-api/mapmyindia-maps-vectorSDK-iOS#7]
**Description** As soon as I import the library, I'm seeing this error. "Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compile"

**Describe the solution you'd like**
https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler
A solution might be to set BUILD_LIBRARY_FOR_DISTRIBUTION to yes.

**Comment by jaindiv26** [comment]
@ayushdayal007 @MapmyIndia-Maps @spacekingindia @mdakram Please help me here, I have a deadline to integrate this SDK into my project, it would really help if you fix this issue ASAP. Same goes for the **Raster SDK** too.

**Comment by ayushdayal007** [comment]
Hi

**Comment by jaindiv26** [comment]
@ayushdayal007 Reason for being closed ?

**Comment by ayushdayal007** [comment]
Hi Divyansh this type of issue occur due to frameworks are not compatiable with your xcode.
please contact apisupport@mapmyindia.com and share your xcode version detail and iOS version you are using in the mail.
You need to change replace your framework , problem will be solved
