### ISSUE TITLE
How I can removed powered by from autocomplete api in code

### ISSUE THREAD

**Issue by manojkraftly** [mappls-api/mapmyindia-maps-vectorSDK-iOS#9]

**Comment by kunalbharti** [comment]
Removal is a violation of MapmyIndia Terms & Conditions: 
This is part of the Terms & Conditions of using MapmyIndia Services. (https://www.mapmyindia.com/api/terms-&-conditions)
See section about 'visible attribution', and branding guidelines: https://www.mapmyindia.com/api/terms-&-conditions.

You can see the following link to tweak it while still following the TnCs: https://github.com/MapmyIndia/mapmyindia-maps-vectorSDK-iOS/wiki/MapmyIndiaUIWidgets#Autocomplete-Attribution-Appearance
